### ISSUE TITLE
Error while configure the scanner for Ratonvirus

### ISSUE THREAD

**Issue by AL-HAYALI** [mainio/ratonvirus-clamby#3]
After I added
Ratonvirus.configure do |config|
  config.scanner = :clamby
end
into the gem file of my app the I ran the code bundle I have got this error:
[!] There was an error parsing `Gemfile`: uninitialized constant #<Class:#<Bundler::Plugin::DSL:0x000055c1d05daa38>>::Ratonvirus. Bundler cannot continue.

 #  from /home/decidim/decidim-app/Gemfile:48
 #  -------------------------------------------
 #
 >  Ratonvirus.configure do |config|
 #    config.scanner = :clamby
 #  -------------------------------------------

**Comment by ahukkanen** [comment]
I have clarified the installation instructions in the README.

Please also read through the Ratonvirus configuration instructions carefully:
https://github.com/mainio/ratonvirus

If you are using Rails, please read through Rails configuration instructions carefully:
https://guides.rubyonrails.org/configuring.html#using-initializer-files

Please also familiarize yourself with what is a Gemfile:
https://bundler.io/gemfile.html

**Comment by AL-HAYALI** [comment]
Thank you.
